model:
  tier: 6
  layers: [8, 5, 4, 3, 2, 2]
  hidden: 512
  gmm: 10
---
accel_data:
  name: 'hyundai'
  path: '/home/skuser/data/stationary_accel_data.pickle'
  extension: '*.wav'
---
sound_data:
  name: 'hyundai'
  path: '/home/skuser/data/stationary_sound_data.pickle'
  extension: '*.wav'
---
audio:
  sr: 8192
  duration: 10.0
  n_mels: 180
  hop_length: 180
  win_length: 500
  n_fft: 300
  num_freq: 769
  ref_level_db: 20.0
  min_level_db: -80.0
---
train:
  num_workers: 1
  optimizer: 'rmsprop'
  sgd:
    lr: 0.0001
    momentum: 0.9
  rmsprop: # from paper
    lr: 0.0001
    momentum: 0.9
  adam:
    lr: 0.0001
  # Gradient Accumulation
  # you'll be specifying batch size with argument of trainer.py
  # (update interval) * (batch size) = (paper's batch size) = 128
  update_interval: 32 # for batch size 1.
---
log:
  summary_interval: 1
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
